services:
  pgvector:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5434:5432"
    volumes:
      - "pgvector_data:/var/lib/postgresql/data"
volumes:
  pgvector_data:
